# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ... }: {
  flake.nixosModules.hostNixos-devHardware = { config, lib, pkgs, modulesPath, ... }: {
    imports =
      [ (modulesPath + "/profiles/qemu-guest.nix")
      ];

    boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
    boot.kernelModules = [ "kvm-intel" ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/d1af9735-304b-40de-9f8d-02af9c98c514";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/E52D-01DB";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  };
}
